### ISSUE TITLE
Add managed identity instead of CM

### ISSUE THREAD

**Issue by thegovind** [Azure/reddog-solutions#18]
- Use managed identity and service connector for the following services
```[tasklist]
### Tasks
- [ ] order-service
- [ ] virtual-customer
- [ ] virtual-worker
- [ ] makeline-service
- [ ] loyalty-service
- [ ] receipt-service
- [ ] accounting-service
```

**Comment by saragluna** [comment]
Hi @thegovind, this should be managed identity instead of workload identity for Azure Spring Apps? And what does CM mean?
