### ISSUE TITLE
Move configs to spring cloud config

### ISSUE THREAD

**Issue by thegovind** [Azure/reddog-solutions#32]
For the following services, move configurations to spring cloud config. There is a local version of this in [local-config-server](https://github.com/Azure/reddog-solutions/tree/main/ancillary/local-config-service/src/main/resources/config) that needs to be updated with the latest configurations for the following repos
```[tasklist]
### Tasks
- [ ] order-service
- [ ] virtual-customer
- [ ] virtual-worker
- [ ] makeline-service
- [ ] loyalty-service
- [ ] receipt-service
- [ ] accounting-service
```

**Comment by moarychan** [comment]
Hi @thegovind , I am going to move the configuration into an independent repository, could you help create a repo for reddog config repository under the Azure org? or we use a branch to store the configurations in the current repo?

**Comment by thegovind** [comment]
I think it's better to keep that in the same repo within a branch, for now, and, if it makes sense later, we can move it into its own repo. We already have too many reddog* repos and it can get very confusing. I also created https://github.com/Azure/asa-workshop and planning to add content on [azsp.net](https://azsp.net) for the workshop, similar to [iappwksp.com](https://iappwksp.com)
