### ISSUE TITLE
asa custom containers for frontend (node.js) and python microservices (az-openai) are failing to start

### ISSUE THREAD

**Issue by thegovind** [Azure/reddog-solutions#34]
- Custom containers on port `1025` are not starting for frontend and python services when deployed to ASA standard

**Comment by moarychan** [comment]
It just deployed successfully, and the frontend page can show the data responded from backend,
![image](https://user-images.githubusercontent.com/19926623/232368597-ab785d8b-17c2-4370-8260-2104d1c8266c.png)

**Comment by LGDoor** [comment]
Can't reproduce this issue. The deployment was successful on my side.

**Comment by saragluna** [comment]
Closing this issue now for cannot reproduce it.
